### PR TITLE
Buffham, a minimal serialization library

### PR DESCRIPTION
**Pull request by RyanDraves**
Add a minimal serialization library with support for:
- schemas & codegen
- messages, transactions, & more codegen

Adjust the base project to use this serialization method.

TODO:
- [x] Test on Pico, see if I run out of stack again

### CODE REVIEW

**Comment by RyanDraves** [comment]
The alignment issues disappeared when I tested it again 🧐 ; guess `memcpy` is smart and I was just running tests before I fixed the offset issues.

**Comment by RyanDraves** [comment]
Tested on the Pico; it works! I can read out the flash from the Pico and it matches my locally compiled `.bin` file. `refl` was indeed, while cool, blowing through the stack with its introspection.

One thing that confuses me is how fast this is. The baud rate is set to `115200` and I can read out the 2 MB flash in as fast as 18.5 seconds. My understanding (and the average internet article) is that 1 symbol = 1 bit, so there's 115200 bps, which would take >2 minutes (ignoring stop/stop bit overhead) to transmit 2 MB. If 1 symbol = 1 byte (maybe with [8-N-1](https://en.wikipedia.org/wiki/8-N-1), we consider the 10 bit frame as one symbol?), we would still expect at least 18.2 seconds to transmit 2 MB. `0.3` seconds of overhead, including everything from how long the client takes to deserialize the response and serialize the next request to the time it takes to transmit that request, is a _hilariously_ small amount of overhead for code running serially with no async patterns. Any thoughts on why this appears so fast? @mark64 or @michael-christen?

One weird thing was that I could set the `read_size` to 2048, which happens to be the size of the Pico's stack. The firmware crashes if I set it even a tiny bit higher, so I presume I was "gracefully" blowing past the stack with other overhead. I set it back to 1024 (which takes ~28 seconds to read) to ignore the problem.

**Comment by marklh0** [comment]
> One thing that confuses me is how fast this is. The baud rate is set to `115200` and I can read out the 2 MB flash in as fast as 18.5 seconds. My understanding (and the average internet article) is that 1 symbol = 1 bit, so there's 115200 bps, which would take >2 minutes (ignoring stop/stop bit overhead) to transmit 2 MB. If 1 symbol = 1 byte (maybe with [8-N-1](https://en.wikipedia.org/wiki/8-N-1), we consider the 10 bit frame as one symbol?), we would still expect at least 18.2 seconds to transmit 2 MB. `0.3` seconds of overhead, including everything from how long the client takes to deserialize the response and serialize the next request to the time it takes to transmit that request, is a _hilariously_ small amount of overhead for code running serially with no async patterns. Any thoughts on why this appears so fast? @mark64 or @michael-christen?

UART speeds are given in baud clocks, that's the number of times per second you can toggle the line (rising + falling). Using those baud clocks, you can transfer a different number of bytes, depending on the number of stop bits and parity enable/disable. So that's why UART speeds, unlike many other protocols, isn't normally written in bytes/s or bps normally. 

For your case with 115200 baud and 8N1, it takes 10 baud clocks to transfer 1 byte (start bit, byte, stop bit).

That means your actual byte rate is 11520 bytes/s.

The idea that you'd only have 0.3 seconds of overhead / 18.5 seconds transfer time is not unreasonable, especially with your custom simplified networking and message serialization stack. That's 292 microseconds per request (assuming 1024 requests). For comparison, the full C++ protobuf implementation can do protobuf decode/encode on both client and server sides in about 200 microseconds.

However, I think that either your math is off, there's a bug in your code, or your UART is running 10x faster than you listed. Transferring 2 MB (assuming you meant 2048x1024 bytes) will take 182 seconds, not 18.2 seconds.

**Comment by mark64** [comment]
Whoops that was from my work GitHub lol

**Comment by RyanDraves** [comment]
Interesting. I'm leaning towards UART being 10x faster than I'm expecting. I'm definitely transferring 2 MB in ~18 seconds and verified the contents with a local copy of the `.bin` file. Glad to know it's pretty low overhead!

**Pull request merged**
